### PR TITLE
add parserOptions

### PR DESCRIPTION
**Pull request by FredericHeem**
Add the possibility to set the parser's option. Needed to work around a bug when *dereferenceSchemas* is set to true.

### CODE REVIEW

**Comment by FredericHeem** [comment]
Do you mind to merge and publish a new npm package ? Many thanks.

**Comment by repocho** [comment]
Hi, sorry about the delay but I didn't receive the email notifications of this pull-request...

**Comment by repocho** [comment]
Merged !! Thanks @FredericHeem for your contribution !! 

I will release a new version soon.

**Comment by FredericHeem** [comment]
Do you mind to publish a new version on npm ? Thanks.

**Comment by repocho** [comment]
It's now published. Thanks again !

**Pull request merged**
